### ISSUE TITLE
Question about the monadic semantic

### ISSUE THREAD

**Issue by meditans** [IagoAbal/haskell-z3#10]
Hi, I have a question regarding the semantics of the monadic interface of this package. Here's an example from the `examples` folder, which I slightly modified adding a slightly different version (grep "take two"):

```haskell
import Z3.Monad
import Control.Monad.Trans (liftIO)
import Control.Monad

run :: IO ()
run = evalZ3 datatypeScript

mkCellDatatype :: Z3 Sort
mkCellDatatype = do
  -- Create a cell data type of the form:
  -- data Cell = Nil | Cons {car :: Cell, cdr :: Cell}

  -- Nil constructor
  nil      <- mkStringSymbol "Nil"
  isNil    <- mkStringSymbol "is_Nil"
  nilConst <- mkConstructor nil isNil []

  -- Cons constructor
  car    <- mkStringSymbol "car"
  cdr    <- mkStringSymbol "cdr"
  cons   <- mkStringSymbol "Cons"
  isCons <- mkStringSymbol "is_Cons"
  -- In the following, car and cdr are the field names. The second argument,
  -- their sort, is Nothing, since this is a recursive sort. The third argument is
  -- 0, since the type is not mutually recursive.
  consConst <- mkConstructor cons isCons [(car,Nothing,0),(cdr,Nothing,0)]

  -- Cell datatype
  cell <- mkStringSymbol "Cell"
  mkDatatype cell [nilConst, consConst]

cons_ :: Z3 AST -> Z3 AST -> Z3 AST
cons_ a b = do
  cell <- mkCellDatatype
  ~[_, consConst] <- getDatatypeSortConstructors cell
  a' <- a
  b' <- b
  mkApp consConst [a', b']
  
nil_ :: Z3 AST
nil_ = do
  cell <- mkCellDatatype
  ~[nilConst, _] <- getDatatypeSortConstructors cell
  mkApp nilConst []

eq_ :: Z3 AST -> Z3 AST -> Z3 AST
eq_ a b = do
  a' <- a
  b' <- b
  mkEq a' b'

not_ :: Z3 AST -> Z3 AST
not_ a = a >>= mkNot

assert_ :: Z3 AST -> Z3 ()
assert_ = (>>= assert)

implies_ :: Z3 AST -> Z3 AST -> Z3 AST
implies_ a b = join (mkImplies <$> a <*> b)

and_ :: [Z3 AST] -> Z3 AST
and_ a = sequence a >>= mkAnd

datatypeScript :: Z3 ()
datatypeScript = do
  cell <- mkCellDatatype
  ~[nilConst, consConst] <- getDatatypeSortConstructors cell

  liftIO $ putStrLn "prove (cons (x,u) = cons(y,v) => x = y && u = v) //Expect Unsat"
  ~[u,v,x,y] <- mapM (flip mkFreshConst cell) ["u","v","x","y"]
  t1 <- mkApp consConst [x,u]
  t2 <- mkApp consConst [y,v]
  p1 <- mkEq t1 t2
  p2 <- mkEq x y
  p3 <- mkEq u v
  p4 <- mkAnd [p2, p3]
  p5 <- mkImplies p1 p4
  push
  mkNot p5 >>= assert
  check >>= liftIO . print
  pop 1

  liftIO $ putStrLn "TAKE TWO: prove (cons (x,u) = cons(y,v) => x = y && u = v) //Expect Unsat"
  push
  assert_ . not_ $ implies_ (eq_ (cons_ (pure x) (pure u)) (cons_ (pure y) (pure v)))
                            (and_ [eq_  (pure x) (pure y), eq_ (pure u) (pure v)])
  check >>= liftIO . print
  pop 1
```

What is the difference between the two versions? I mean, in particular, what happens in the underlying monad if I call multiple times
```haskell
mkDatatype cell [nilConst, consConst]
```
Is it semantically equal but adds cruft in the solver?

**Comment by IagoAbal** [comment]
Hi,

> what happens in the underlying monad if I call multiple times `mkDatatype cell [nilConst, consConst]`

Good question, but I don't know the answer without trying it out. I would expect an error, but the [official C API documentation](https://z3prover.github.io/api/html/group__capi.html#ga34875df69093aca24de67ae71542b1b0) is not precise about this. Have you tried it out?

**Comment by meditans** [comment]
Sure, i tried it out and I couldn't observe any error or suspicious behavior; I was mainly concerned that I could introduce some weird duplication of work in the underlying solver slowing it down.

A bit about the motivation for this question: if repeating these instruction is in fact a no-op, one could write a generic interface that wrote them every time they are used (for example, when introducing a variable of type `Foo`, automatically inserting the z3 definition of `Foo` so that the user doesn't have to do it himself.

I suppose I'll watch out for errors then, and please ping me if you think of a way of understanding how the C API behaves.

_ps._ speaking of the C API, are your links to the documentation in the source code up to date? They redirect me to a microsoft presentation page.

**Comment by meditans** [comment]
@NikolajBjorner could you shed light on this issue: what happens if I call multiple times with the same arguments the C function [z3_mk_datatype](http://z3prover.github.io/api/html/group__capi.html#ga34875df69093aca24de67ae71542b1b0)? Do I cause an error? Do I slow the solver? In general, which functions are referentially transparent in the z3 API?

**Comment by IagoAbal** [comment]
> A bit about the motivation for this question: if repeating these instruction is in fact a no-op, one could write a generic interface that wrote them every time they are used (for example, when introducing a variable of type `Foo`, automatically inserting the z3 definition of `Foo` so that the user doesn't have to do it himself.

If I were you I would try to make sure to add type `Foo` just once. This would make your work a bit harder, but it would be more robust.
 
> I suppose I'll watch out for errors then, and please ping me if you think of a way of understanding how the C API behaves.

You could always look into the API implementation. Or you can run some experiments re-declaring the same data-type a huge number of times and see what effect that has.

> _ps._ speaking of the C API, are your links to the documentation in the source code up to date? They redirect me to a microsoft presentation page.

The may not be up-to-date anymore... I have switched to OCaml land and I do very little Haskell nowadays. I try to keep this project alive by helping others to contribute and reviewing pull requests, but ultimately it's the people who use it who should keep it up-to-date!

**Comment by NikolajBjorner** [comment]
Z3 maintains overwrites the previous definitions with the new identical one. It isn't going to be resilient against multiple versions of a datatype with the same name but different constructors.
