### ISSUE TITLE
MonadFail and GHC 8.6+

### ISSUE THREAD

**Issue by conal** [IagoAbal/haskell-z3#33]
It looks like the z3 library doesn’t play nicely with [the `MonadFail` desugaring changes starting in GHC 8.6](https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.6#monadfaildesugaring-by-default). I’ll submit a pull request shortly.

**Comment by IagoAbal** [comment]
Thanks for contributing, this was fixed by 70471b902a4339e26f5e850c5724c180aeee8220.
