### ISSUE TITLE
Runtime incompatibility with z3 >= 4.8 (undefined symbol: Z3_get_parser_error)

### ISSUE THREAD

**Issue by srhb** [IagoAbal/haskell-z3#9]
z3 4.7.1 is the last version to contain the symbol Z3_get_parser_error. This causes runtime failures in haskell-z3 with newer versions of z3.

Please note that the upstream API docs have not been regenerated since 4.8 was released, so the github hosted docs still claim to contain it, while the source (or indeed a fresh regeneration of the docs) do not. I don't know why it was removed, but it appears to have been done intentionally:

https://github.com/Z3Prover/z3/commit/1eb8ccad59b8ea2c12b1ec8e7e712c7891b252d0#diff-d6c80d51fca9ba3afd43693f09f35c1dL5288

**Comment by Infinisil** [comment]
Pinging the committer of the above, @NikolajBjorner

**Comment by NikolajBjorner** [comment]
Make sure not to link older version of Z3 with newer runtimes.

**Comment by IagoAbal** [comment]
@srhb if you make it work with 4.8, can you open a pull request? Thanks.

**Comment by IagoAbal** [comment]
This should have been fixed by pull request #13 by @meditans. Please ping me if this doesn't work for you.

I shall tag haskell-z3 and upload a new version to Hackage soon.

**Comment by IagoAbal** [comment]
I have released [408.0](http://hackage.haskell.org/package/z3-408.0) to support Z3 4.8, let me know if it doesn't work.

@meditans @strake
